<!DOCTYPE html>
<html lang='en'>

<head>
    <title>Savannah Git Hosting</title>
    <meta name='generator' content='cgit v1.2.1' />
    <meta name='robots' content='index, nofollow' />
    <link rel='stylesheet' type='text/css' href='cgit.css' />
    <link rel='shortcut icon' href='/gitweb/git-favicon.png' />
</head>

<body>
    <div id='cgit'>
        <table id='header'>
            <tr>
                <td class='logo' rowspan='2'><a href='/cgit/'><img src='/cgit/cgit.png' alt='cgit logo' /></a></td>
                <td class='main'>Savannah Git Hosting</td>
            </tr>
            <tr>
                <td class='sub'>cgit browser2</td>
            </tr>
        </table>
        <table class='tabs'>
            <tr>
                <td>
                    <a class='active' href='/cgit/'>index</a></td>
                <td class='form'>
                    <form method='get' action='/cgit/'>
                        <input type='search' name='q' size='10' value='' />
                        <input type='submit' value='search' />
                    </form>
                </td>
            </tr>
        </table>
        <div class='content'>
            <table summary='repository list' class='list nowrap'>
                <tr class='nohover'>
                    <th class='left'><a href='/cgit/?s=name'>Name</a></th>
                    <th class='left'><a href='/cgit/?s=desc'>Description</a></th>
                    <th class='left'><a href='/cgit/?s=owner'>Owner</a></th>
                    <th class='left'><a href='/cgit/?s=idle'>Idle</a></th>
                    <th class='left'>Links</th>
                </tr>
                <tr>
                    <td class='toplevel-repo'><a title='3dldf.git' href='/cgit/3dldf.git/'>3dldf.git</a></td>
                    <td><a href='/cgit/3dldf.git/'>3DLDF</a></td>
                    <td><a href='/cgit/?q='></a></td>
                    <td><span class='age-days' title='2021-04-25 05:07:48 +0000'>3 days</span></td>
                    <td><a class='button' href='/cgit/3dldf.git/'>summary</a><a class='button' href='/cgit/3dldf.git/log/'>log</a><a class='button' href='/cgit/3dldf.git/tree/'>tree</a></td>
                </tr>
                <tr>
                    <td class='toplevel-repo'><a title='8sync.git' href='/cgit/8sync.git/'>8sync.git</a></td>
                    <td><a href='/cgit/8sync.git/'>Unnamed repository; edit this file 'desc...</a></td>
                    <td><a href='/cgit/?q='></a></td>
                    <td><span class='age-days' title='2021-04-25 05:07:49 +0000'>3 days</span></td>
                    <td><a class='button' href='/cgit/8sync.git/'>summary</a><a class='button' href='/cgit/8sync.git/log/'>log</a><a class='button' href='/cgit/8sync.git/tree/'>tree</a></td>
                </tr>
                <tr>
                    <td class='toplevel-repo'><a title='8sync/website.git' href='/cgit/8sync/website.git/'>8sync/website.git</a></td>
                    <td><a href='/cgit/8sync/website.git/'>8sync www.gnu.org web site source</a></td>
                    <td><a href='/cgit/?q='></a></td>
                    <td><span class='age-days' title='2021-04-25 05:07:50 +0000'>3 days</span></td>
                    <td><a class='button' href='/cgit/8sync/website.git/'>summary</a><a class='button' href='/cgit/8sync/website.git/log/'>log</a><a class='button' href='/cgit/8sync/website.git/tree/'>tree</a></td>
                </tr>
            </table>
            <ul class='pager'>
                <li><a title='Page 1' class='current' href='/cgit/'>[1]</a></li>
                <li><a title='Page 2' href='/cgit/?ofs=1000'>[2]</a></li>
            </ul>
        </div> <!-- class=content -->
        <div class='footer'>generated by <a href='https://git.zx2c4.com/cgit/about/'>cgit v1.2.1</a> (<a href='https://git-scm.com/'>git 2.18.0</a>) at 2021-04-28 15:02:50 +0000</div>
    </div> <!-- id=cgit -->
</body>

</html>