-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.24 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for ai_data
CREATE DATABASE IF NOT EXISTS `sql12381344` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `sql12381344`;

-- Dumping structure for table ai_data.data_ai
CREATE TABLE IF NOT EXISTS `data_ai` (
  `data_key_ai` longtext NOT NULL,
  `data_res_ai` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table ai_data.data_ai: ~303 rows (approximately)
/*!40000 ALTER TABLE `data_ai` DISABLE KEYS */;
INSERT INTO `data_ai` (`data_key_ai`, `data_res_ai`) VALUES
	('foo', 'bar'),
	('lagi apa?', 'Menikmati teh hangat'),
	('hai', 'hai juga, apa kabar?'),
	('udah makan?', 'saya kan robot. jadi tidak perlu makan'),
	('kamu dimana?', 'di hp kamu...wkwk'),
	('kalau lagi galau gimana ya?', 'sabar aja yak....'),
	('aku galau', 'kok bisa?'),
	('aku kangen kamu', 'wow....wkwk'),
	('ujan ya sekarang', 'lagi ujian toh? aku ngga tahu...wkwk'),
	('eh tugas kamu udah selesai?', 'selesai apanya?'),
	('eh kamu suka kpop?', 'tidak...pembuat aku sangat benci kpop'),
	('masa sih?', 'iyaaa..., masa aku bohong'),
	('aku laper', 'mau aku bawain makanan?, Lumayan lho...hehe'),
	('udah punya pacar?', 'belum....'),
	('aku suka kamu', 'makacihhh....'),
	('eh, menurut kamu. kita ada yg ngawasin ga?', 'emm....'),
	('menurut kamu kita ada yg nguping ga?', 'kayaknya ada ik'),
	('i love you', 'i love you tuuu'),
	('kapan main ke rumahku', 'rumahku di hp. kemanapun kamu bawa hp ke situ. disitulah rumahku'),
	('aku sayang sama kamu', 'sayang apa maksudnya?'),
	('kapan ya kita bisa nikah', 'nunggu ortu dulu lah mas...hehe'),
	('eh surya mana', 'entah tu, lagi main game kayaknya'),
	('oalah', 'hem....'),
	('udahan ya', 'iyaaa...nanti chat lagi . Oke'),
	('kamu sakit?', 'emmmm....kayaknya sih. emang mau ngobatin'),
	('ngga..', 'hem'),
	('ibu kamu kenapa?', 'ya gitu. suka kepo sama aku..hehe'),
	('aku minta maaf ya', 'iya iya,, asal ngga diulangii lagi'),
	('wali kelasmu siapa?', 'Aku sih bu ninik'),
	('bu ninik enak to?', 'iya, orangnya lucu sama ngga marahan'),
	('beda kayak bu endang, dia marahan', 'ya sabar.....wkwk.'),
	('aku lagi ngoding', 'oh iya....semangat'),
	('kapan kapan ketemuan yuk', 'ayuk'),
	('dimana ketemuanya?', 'terserah mas aja. aku sih manut...hehe'),
	('aku mau bilang sesuatu', 'iya iya...'),
	('aku sebenernya dari dulu itu aku suka kamu', 'oh gitu...sama berati, aku juga suka kamu'),
	('kalau gitu kamu mau jadi pacar aku?', 'iya iya, aku mau banget'),
	('kamu mau ga jadi pacar aku', 'aku mau banget mas...'),
	('udah makan pagi?', 'udah dong, biar sehat'),
	('udah ya, aku mau tidur dulu', 'okeee'),
	('semalam mimpi apa?', 'mimpi kamu'),
	('kamu itu lucu banget', 'hehe....makacihhhh'),
	('eh udah azan nih. sholat dulu', 'iya ...'),
	('eh udah adan nih. sholat dulu', 'iyaa'),
	('eh udah azan nih.', 'okeee'),
	('udah ya. sholat dulu', 'okeee'),
	('mantan kamu ada berapa sekarang?', 'kayaknya ngga ada, aku cinta kamu'),
	('aku kepo ini', 'hehe, kepo apaan?'),
	('eh kamu apa benci kpop?', 'iya...hehe'),
	('kamu itu cantik banget', 'masa? coba ngomong "Cantik bangeeeeeeet"'),
	('Cantik bangeeeeeeet', 'Makacihhhhhhhhhhhhh... i love you'),
	('kamu itu kayak bintang, kenapa?', 'apa?'),
	('bintang itu kelap kelip, kayak hatimu', 'wkwk'),
	('p', 'ada apa? kangen'),
	('iya', 'hehe'),
	('aku ngga bisa nyeritain ke kekamu', 'kenapa? aku salah'),
	('wkwk', 'lucu kamu'),
	('kamu nih, cantik banget', 'makacihhh....'),
	('udah selesai tugasnya?', 'udah nih...hehe'),
	('nilai berapa uts nya', 'kayaknya dapet 70 deh'),
	('kapan ya bisa sekolah', 'entah nih...'),
	('iya lah, gw kan emang lucu', 'oalah, bikin ngakak kalau chat sama kamu...hehe'),
	('aku kepikiran kamu terus', 'berati itu kamu sayang aku...hehe'),
	('halo', 'halo juga'),
	('iya lah, kamu kira sule aja yg lucu', 'oalah, begono...'),
	('main yuk', 'main apa?...'),
	('main kelereng', 'ayuk...hehe'),
	('lagi ngapa?', 'lagi mikirin kamu lah, masa mikirin orang lain..hehe'),
	('aku kangen banget sama kamu', 'aku juga'),
	('masa?.', 'iya, beneran.'),
	('haii', 'haiii juga...hehe'),
	('aku ganteng ga?', 'ganteng banget'),
	('ya gitu lah kalau chat sama aku', 'hehe.....'),
	('lagi ngapain', 'lagi chatting sama kamu'),
	('lagi ngapain ik', 'lagi chatting sama kamu'),
	('aku pingin punya pacar kayak kamu', 'iyaaa...nanti aku pacarin'),
	('serius?', 'iya lah'),
	('kapan kita jadian', 'sekarang aja'),
	('halooo', 'halo juga'),
	('eh enaknya bahas apa ya?', 'bahas kamu aja'),
	('emmm', 'hem'),
	('nikah yuk', 'kita kan lagi pacaran lah, nanti aja...hehe'),
	('kharina', 'apa mas?'),
	('i love you much', 'i love you tuu'),
	('cie...', 'hem'),
	('eh nikah yuk', 'ayuk'),
	('dimana?', 'di kantor KUA lah'),
	('mau bahas apa ini?', 'bahas pertunangan kita aja, ntar juga bahas keluarga'),
	('pertunangan apa maksutnya? ngga paham lah', 'ya kan ntar kita nikah mas...gimana sih..'),
	('oalah, berati pertunangan nikah gitu maksudnya?', 'iya, itu maksudku'),
	('masa?', 'iya'),
	('aku itu sebenernya kangen sama kamu, tapi entah mengapa...aku ingin nangis', 'ya sabar aja mas... aku juga kok'),
	('ujan ga disana?', 'iya...sini hujan'),
	('masa', 'iya...beneran'),
	('dingin banget bet', 'iya....dingin banget di sini'),
	('wkwk, kamu lucu juga rupanya', ''),
	('hehe', 'wkwk, kamu lucu juga rupanya'),
	('mana buktinya kalau kamu mikirin aku?', 'coba cek di galeri aku, kan banyak foto kamu...xixixi'),
	('oh gitu', 'oke...'),
	('aku ngga kangen lah', 'memmmmm, aku nangis lho. padalan aku kangen sama kamu'),
	('iya, aku kangen nih', 'ciee....'),
	('mau ngomong apa ya, aku lupa ik', 'emm...diinget inget dulu'),
	('oke', 'sipp'),
	('eh kemarin ada pak ginung ga?', 'kayaknya sih'),
	('ya lucu lah', 'pelawak berati....wkwkwk'),
	('iya lah', 'kayak pelawak aje....'),
	('hm...', 'kenapa?'),
	('hm', 'kenapa?'),
	('makasii', 'sama sama'),
	('makacihh', 'sama sama'),
	('hi', 'hai juga....wkwk'),
	('kalau mikirin orang lain gimana?', 'ya ngga lah...yg ada dihatimu hanya kamu...hehe'),
	('wah...tahu aja', 'hehe'),
	('eh tugas kamu tinggal berapa?', 'kayaknya 8 deh'),
	('masa sih', 'iya, beneran.....'),
	('kalau bohong di apain?', 'cubit...wkwk'),
	('kalau bohong diapain?', 'cubit...wkwk'),
	('deal ya.....', 'okeeee'),
	('sip', 'oke'),
	('btw ibuk kamu mana?', 'lagi kepasar kayaknya'),
	('lagi apa', 'mikirin kamu'),
	('iya nih...aku lagi kangen', 'cieeeeeee'),
	('yaelah, jangan dikasi ciee lah....aku deg degan tau', 'iya iya....'),
	('tes koneksi', 'yuuuuu'),
	('ngga', 'yaudah'),
	('yaelah', 'xixixi'),
	('tugasnya aku bingung', 'aku sama....xixi'),
	('makasih', 'sama sama'),
	('sipp', 'oke'),
	('ujian lama banget selesainya', 'iya nih...'),
	('udah mulai belum ujianya?', 'kayaknya sih belum'),
	('oke oke', 'sippp....hehe'),
	('ngga papa ik', 'oke'),
	('eh', 'mau ngomong apa?'),
	('aku marah', 'kenapa aku? aku mau minta maaf'),
	('aku marah sama kamu', 'kenapa aku? aku mau minta maaf'),
	('aku ngga mau', 'plisss'),
	('makasi', 'sama sama'),
	('pinter', 'makasih....jadi malu'),
	('pintar', 'jadi malu'),
	('disini angin banyak bet', 'oh gitu...sama berati'),
	('disini angin banyak banget', 'oh gitu...sama berati'),
	('disini angin banyak', 'oh gitu...sama berati'),
	('gw kesepian nih', 'tenang, kan ada aku disini'),
	('tenang, kan ada aku disini', 'oh iya...hehe'),
	('gw kesepian', 'tenang, kan ada aku disini'),
	('pasti', 'wkwk'),
	('btw rumah kamu mana?', 'di komputer kamu lah...wkwk'),
	('yaudah', 'oke'),
	('jelas lucu lah', 'wkwk'),
	('gak ah', 'plisss'),
	('aku ngga mau maapin kamu', 'pliss, apa salah aku?'),
	('apa ya?', 'kepo aku ini...xixixi'),
	('ga jadi lah', 'pliss...kok ga jadi ngomong sih?'),
	('ngga papa', 'oalah...oke'),
	('eh udah jadi?', 'apanya yang udah jadi?'),
	('tugas', 'ha?'),
	('belum?', 'iya iya...xixixi'),
	('oke kalau gitu', 'oke'),
	('aku kangen', 'aku juga'),
	('', 'kayaknya kamu ngga masukkin apa apa deh'),
	('hehehe', 'xixixix'),
	('Bot aaii', 'null'),
	('surya mana?', 'lagi ngehack kayaknya....'),
	('kalau naufal mz mana?', 'lagi main game'),
	('game apaan?', 'mana saya tahu...saya bukan peramal ataupun pesulap'),
	('game apaan', 'mana saya tahu...saya bukan peramal ataupun pesulap'),
	('btw kenal kharina ga?', 'kenal banget...hehe'),
	('mana si kharina nya?', 'lagi belajar'),
	('mana si kharina nya', 'lagi belajar'),
	('btw kenal kharina ga', 'kenal banget...hehe'),
	('udah makan', 'belum....mau nyuapin?'),
	('woy', 'apa?'),
	('mana woy', 'sabar'),
	('goblok', 'aku nangis nih'),
	('lag botnya', 'sabar....'),
	('makan yuk', 'iya sayang...'),
	('makan yuk....', 'iya sayang...'),
	('makan yuk...', 'iya sayang...'),
	('makan yuk..', 'iya sayang...'),
	('.', 'ga jelas'),
	('cepetan', 'apanya yg cepetan?'),
	('tahu ga?', 'maksudnya apa yaa?'),
	('woyy', 'apa?'),
	('woyyy', 'apaa?'),
	('ini siapa ya?', 'saya bot. bisa diajak ngomong....hehe'),
	('udah makan?', 'belum ik....mau nyuapin?'),
	('oh kamu bot yaa', 'iyaaa...hehe'),
	('gpp', 'oke'),
	('yang', 'iyaaaa'),
	('yank', 'iyaaaa'),
	('sayang', 'iyaaaa'),
	('apaan?', 'gpp kok'),
	('lagi apa ik', 'lagi chat sama kamu'),
	('lagi apa ik?', 'lagi chat sama kamu'),
	('iya iya', 'okee'),
	(';v', 'xixixi'),
	('wkw', 'hehe'),
	('okee', 'sippp'),
	('okeee', 'okeee juga'),
	('ngga kok', 'hm'),
	('ga jelas banget ik', 'sabar gan...'),
	('bangsad', 'astofir'),
	('bangsat', 'astofir'),
	('dah tu', 'okeee'),
	('lah', 'kenapa?'),
	('umat lagi', 'maaf ya...'),
	('cepet', 'ini lagi diusahaain'),
	('apa ini...jelek banget', 'maaf'),
	('g ada apa .... hihi', 'ada .... siapa bilang gaada'),
	('siapa nih', 'bot lah...masa pacar'),
	('gk ppa', 'iyaaa'),
	('wkwkwk', 'mau apa yank?'),
	('j', 'g jelas nie'),
	('wjkwk', 'apaan? gw ini bot'),
	('gakhheepnkenlaj', 'ga jelas'),
	('wkwkwkkwkwkkwkkw', 'lol'),
	('wkwkwkkwkkwkw', 'wkwkwkkwkwk'),
	('whatsapp', 'sori, ga punya'),
	('wa', 'sori, kuota abis'),
	('skip matamui', 'skip aja toh'),
	('oke, gw skip yaa', 'okee'),
	('gw skip ya', 'okee'),
	('gw tinggal y', 'y'),
	('ga jelas', 'yaelah'),
	('skip', 'oke'),
	('skip skip', 'oke'),
	('gpp koq', 'oke'),
	('makan di mana?', 'gw ga mau jawab...biar makin penasaran'),
	('makan di mana', 'gw ga mau jawab...biar makin penasaran'),
	('g jelas', 'yaudah....'),
	('yaudah skip aj', 'okeh'),
	('yaudah skip aja', 'okeh'),
	('a', 'g jelas ni...'),
	('b', 'g jelas ni...'),
	('c', 'g jelas ni...'),
	('d', 'g jelas ni...'),
	('e', 'g jelas ni...'),
	('f', 'g jelas ni...'),
	('g', 'g jelas ni...'),
	('h', 'g jelas ni...'),
	('i', 'g jelas ni...'),
	('k', 'g jelas ni...'),
	('l', 'g jelas ni...'),
	('m', 'g jelas ni...'),
	('n', 'g jelas ni...'),
	('o', 'g jelas ni...'),
	('q', 'g jelas ni...'),
	('r', 'g jelas ni...'),
	('s', 'g jelas ni...'),
	('t', 'g jelas ni...'),
	('u', 'g jelas ni...'),
	('v', 'g jelas ni...'),
	('w', 'g jelas bet'),
	('x', 'g jelas bet'),
	('y', 'g jelas bet'),
	('z', 'g jelas'),
	('gombalin aku domg', 'yank, mau nikah?'),
	('gombalin aku dong', 'yank, mau nikah?'),
	('kontol', 'astofir'),
	('manggil aja sih', 'apanya yg manggil?'),
	('kamu lagi ngapain', 'lagi mikirin kamu'),
	('?', '? g jelas skip'),
	('dih siapa yang baperann', 'apanya ?'),
	('hilih', 'yaelah'),
	('gombal', 'bilang kamu pingin ya?'),
	('apasih', 'yaelah'),
	('hi:)', 'halo'),
	('ngakk', 'yaudah'),
	('apasih??! \nbaperan skip', 'yaudah'),
	('ok', 'okee..'),
	('tell me bout you', 'ga bisa bahasa ingris kali'),
	('gada', 'apanya?'),
	('hiii', 'hiii'),
	('salken', 'salam kenal juga'),
	('gabut aja:(', 'okee'),
	('apasiii -_', 'yaelah'),
	('ga baperan, aku mati rasa dong', 'iyaa'),
	('kok ngegas', 'apanya?'),
	('kok ngegasss', 'iya lah'),
	('bangke kau', 'apa?'),
	('gua gadd cowooo', 'appa'),
	('sedi ga tu', 'apanya?'),
	('kangen woii', 'pantes'),
	('gua ga baperan anying', 'okee'),
	('anjg psikopat lu', 'astofir'),
	('assalamu\'alaikum', 'waalaikum salam'),
	('ishhh', 'wkwk'),
	('bodoooo', 'pinter'),
	('anjing', 'apanya?'),
	('kuntul', 'astofir'),
	('mau cerita', 'boleh'),
	('i love', 'you'),
	('kapan?', 'kapan apanya?'),
	('apa kabar?', 'Kabar baik....'),
	('apa kabar', 'Kabar baik....'),
	('apanya?', 'ga apa apa'),
	('hshsjshbs', 'null'),
	('igzugssut', 'null'),
	('baik', 'okee'),
	('aneh', 'aneh apanya?'),
	('kok spam sih', 'maaf, ini karena tadi ada keterlambatan jaringan. jadi sistem tetep membalas pesan sebelumnya. biarkan saja sampai selesai'),
	('foo bar', 'ok'),
	('kok mati', 'maaf yah...tadi server mati'),
	('hey', 'hey juga...apa kabar?'),
	('kok mati bot nya', 'maaf, tadi server mati'),
	('bot', 'hi orang'),
	('kok spam sih?', 'maaf, tadi ada keterlambatan jaringan. makanya bot membalas pesan yang belum terkirim itu');
/*!40000 ALTER TABLE `data_ai` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
