<?php
$reply = 'theme yang disupport di photooxy' . PHP_EOL . PHP_EOL .
    '/shadow
/flower_cup
/romantic_messages
/burn_paper
/funny_cup
/hand_love
/grass
/tiktok
/red_heart
/coffe
/wood_heart
/wooden_board
/3d_summer
/wolf_metal
/nature_3d
/underwater
/golden_rose
/summer_nature
/leaf
/fall_leaves
/neon
/rainbow
/army_camouflage_fabric
/3d_glowing
/vintage
/candy_text
/white_cube
/green_leaves
/avatar_gradient
/glow_rainbow
/stars
/fur
/flaming
/chrome
/embroidery
/3d_rainbow_background
/metalic
/striking
/watermelon
/web_matrix
/multi_material
/butter_fly
/wooden_3d
/modern_metal
/harry_poter
/3bit
/coffe_cup
/luxury_royal
/scary
/woodblock
/smoke
/sweet_candy
/silk
/royal
/orchids_flower
/flower
/party_neon
/dark_metal';
$content = array('chat_id' => $chat_id, 'text' => $reply, 'reply_to_message_id' => $message_id, 'parse_mode' => 'html', 'disable_web_page_preview' => true);
$telegram->sendMessage($content);
